preload=/home/enainandreev/.config/hypr/wallpapers/wallpaper1.webp
preload=/home/enainandreev/.config/hypr/wallpapers/bg_wallpaper2.png
wallpaper {
    monitor = DP-2
    path = /home/enainandreev/.config/hypr/wallpapers/wallpaper1.webp
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/enainandreev/.config/hypr/wallpapers/bg_wallpaper2.png
    fit_mode = cover
}