conky.config = {
    out_to_x = false,
    out_to_wayland = true,
    own_window = true,
    own_window_type = 'dock',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    
    alignment = 'top_right',
    gap_x = 30,
    gap_y = 60,
    minimum_width = 320,
    update_interval = 1.0,
    
    double_buffer = true,
    use_xft = true,
    font = 'JetBrainsMono Nerd Font Mono:size=10',
    default_color = 'D8DEE9',
    color1 = '88C0D0', -- Nord blue
    lua_load = '/home/enainandreev/.config/conky/visualizer.lua',
}

conky.text = [[
${color1}WELCOME ${hr 2}
${color}Добро пожаловать, командир ${execi 600 whoami}! O7
${color}Реактор: ${alignr}${nodename}
${color}Ядро: ${alignr}${kernel}

${color1}SYSTEM LOAD ${hr 2}
${color}CPU Total: ${alignr}${cpu cpu0}%
${color}RAM Usage: ${alignr}${mem} / ${memmax} (${memperc}%)
${color}Uptime: ${alignr}${uptime}

${color1}AMD GPU ${hr 2}
${color}GPU Load: ${alignr}${execi 1 cat /sys/class/drm/card0/device/gpu_busy_percent}%
${color}GPU Temp: ${alignr}${execi 1 sensors | grep 'edge' | awk '{print $2}' | cut -c2-}
${color}VRAM Usage: ${alignr}${execi 1 expr $(cat /sys/class/drm/card0/device/mem_info_vram_used) / 1048576} MB

${color1}TOP PROCESSES ${hr 2}
${color}${top name 1} ${alignr}${top cpu 1}%
${color}${top name 2} ${alignr}${top cpu 2}%
${color}${top name 3} ${alignr}${top cpu 3}%

${color1}AUDIO ${hr 2}
${color}Volume: ${alignr}${execp wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100 "%"}'}
]]